#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("DelClima.Droid.Resource", IsApplication=true)]

namespace DelClima.Droid
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
			global::Plugin.Fingerprint.Resource.Drawable.fingerprint_white = global::DelClima.Droid.Resource.Drawable.fingerprint_white;
			global::Plugin.Fingerprint.Resource.Id.fingerprint_btnCancel = global::DelClima.Droid.Resource.Id.fingerprint_btnCancel;
			global::Plugin.Fingerprint.Resource.Id.fingerprint_btnFallback = global::DelClima.Droid.Resource.Id.fingerprint_btnFallback;
			global::Plugin.Fingerprint.Resource.Id.fingerprint_imgFingerprint = global::DelClima.Droid.Resource.Id.fingerprint_imgFingerprint;
			global::Plugin.Fingerprint.Resource.Id.fingerprint_txtReason = global::DelClima.Droid.Resource.Id.fingerprint_txtReason;
			global::Plugin.Fingerprint.Resource.Layout.FingerprintDialog = global::DelClima.Droid.Resource.Layout.FingerprintDialog;
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int fingerprint_white = 2130837504;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f06000c
			public const int btnLimpiarApp = 2131099660;
			
			// aapt resource value: 0x7f06000b
			public const int btnVerClima = 2131099659;
			
			// aapt resource value: 0x7f060016
			public const int condSection = 2131099670;
			
			// aapt resource value: 0x7f060002
			public const int fingerprint_btnCancel = 2131099650;
			
			// aapt resource value: 0x7f060003
			public const int fingerprint_btnFallback = 2131099651;
			
			// aapt resource value: 0x7f060000
			public const int fingerprint_imgFingerprint = 2131099648;
			
			// aapt resource value: 0x7f060001
			public const int fingerprint_txtReason = 2131099649;
			
			// aapt resource value: 0x7f06000a
			public const int getSection = 2131099658;
			
			// aapt resource value: 0x7f060013
			public const int humidSection = 2131099667;
			
			// aapt resource value: 0x7f060005
			public const int latLabel = 2131099653;
			
			// aapt resource value: 0x7f060004
			public const int latSection = 2131099652;
			
			// aapt resource value: 0x7f060006
			public const int latText = 2131099654;
			
			// aapt resource value: 0x7f060018
			public const int lblCondiciones = 2131099672;
			
			// aapt resource value: 0x7f060017
			public const int lblCondicionesText = 2131099671;
			
			// aapt resource value: 0x7f060015
			public const int lblHumedad = 2131099669;
			
			// aapt resource value: 0x7f060014
			public const int lblHumedadText = 2131099668;
			
			// aapt resource value: 0x7f060012
			public const int lblTemperatura = 2131099666;
			
			// aapt resource value: 0x7f060011
			public const int lblTemperaturaText = 2131099665;
			
			// aapt resource value: 0x7f06000f
			public const int lblUbicacion = 2131099663;
			
			// aapt resource value: 0x7f06000e
			public const int lblUbicacionText = 2131099662;
			
			// aapt resource value: 0x7f06000d
			public const int locSection = 2131099661;
			
			// aapt resource value: 0x7f060008
			public const int longLabel = 2131099656;
			
			// aapt resource value: 0x7f060007
			public const int longSection = 2131099655;
			
			// aapt resource value: 0x7f060009
			public const int longText = 2131099657;
			
			// aapt resource value: 0x7f060010
			public const int tempSection = 2131099664;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f040000
			public const int FingerprintDialog = 2130968576;
			
			// aapt resource value: 0x7f040001
			public const int Main = 2130968577;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class Mipmap
		{
			
			// aapt resource value: 0x7f030000
			public const int Icon = 2130903040;
			
			static Mipmap()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Mipmap()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f050001
			public const int app_name = 2131034113;
			
			// aapt resource value: 0x7f050000
			public const int hello = 2131034112;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
	}
}
#pragma warning restore 1591
